import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, resolve } from 'path';
import process from 'process';

const root = resolve(new URL('../', import.meta.url).pathname);
const outDir = resolve(root, 'dist');
const isWatch = process.argv.includes('--watch');

async function bundle() {
  await mkdir(outDir, { recursive: true });
  await build({
    entryPoints: [resolve(root, 'src/main.ts')],
    bundle: true,
    outfile: resolve(outDir, 'main.js'),
    format: 'esm',
    target: 'es2018',
    platform: 'browser',
    sourcemap: false,
    banner: {
      js: '// Generated by esbuild. Do not edit.\n'
    },
    watch: isWatch
      ? {
          onRebuild(error) {
            if (error) {
              console.error('Rebuild failed:', error);
            } else {
              console.log('Rebuild succeeded.');
            }
          }
        }
      : false,
  });

  const manifestSrc = resolve(root, 'manifest.json');
  const manifestDst = resolve(outDir, 'manifest.json');
  const manifestContents = await readFile(manifestSrc, 'utf-8');
  await writeFile(manifestDst, manifestContents, 'utf-8');
}

bundle().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
